### ISSUE TITLE
No funcionan clases de colores

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/InteligenciaSatelital#2]
Intento colocar color a mis h1 y h3 de la siguiente manera:

%img{src: "img/IS_Logo.jpg", :alt => "No se ve ni merga"}
						.caption.center-align
							%h1.negro-text Conócenos
							%h3 Conoce a I.S
Pero no realiza ningún cambio, en cambio, si utilizo la siguiente línea si funciona el color

%img{src: "img/IS_Logo.jpg", :alt => "No se ve ni merga"}
						.caption.center-align
							%h1{:style => "color: #333333;"} Conócenos
							%h3 Conoce a I.S

**Comment by Topi99** [comment]
Ya funcionan, el problema eran las comillas en el _colores.scss
